name: walletconnect_dart
description: Open protocol for connecting decentralised applications to mobile wallets with QR code scanning or deep linking.
version: 0.0.11
homepage: https://walletconnect.org/
repository: https://github.com/RootSoft/walletconnect-dart-sdk
issue_tracker: https://github.com/RootSoft/walletconnect-dart-sdk/issues

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  # WebSocket Channel
  web_socket_channel: ^3.0.3

  # UUID
  uuid: ^4.0.0

  # Cryptography
  cryptography: ^2.7.0

  # Hex
  convert: ^3.1.2

  # JSON Annotation
  json_annotation: ^4.9.0

  # Stack trace
  stack_trace: ^1.12.1

dev_dependencies:
  # Testing framework
  test: ^1.20.1

  # JSON Serialization
  json_serializable: ^6.10.0

  # Build runner
  build_runner: ^2.6.0